Local art resolver
Proximity-Engine/Proximity pull request #26
Opened 2021-10-03 20:55 UTC by Gikkman

Implements a resolver for finding local art. This resolver looks in a folder called `art` located at `$PWD` at the time of execution (i.e. next to the proximity.jar, or in the root of the java project).

If no local art is found, or the `art` directory doesn't exist, it falls back to using the old resolver.

If the `--use_official_art` flag is not set to true, the ArtLayer won't be rendered anyway.

------------
There are some caveats to this implementation that I would like some input on, and I am not entire sure how we should handle it. I implemented a way to assign a set to an image, and if a set it assigned, it trumps images with a set assigned (given that you try to render a card of said set). But every card that is rendered has a set by default, since scryfall defaults to the latest printing of a card if no set is explicitly assigned.

So say you want to render:
```
1 Counterspell
1 Counterspell (MH2)
```
And you got two images:
```
art/counterspell.jpg
art/mh2/counterspell.jpg
```
In this case, I would assume the creator would like one counterspell of each art to be rendered, since they assigned set to one of them and not to the other. But in reality, since MH2 is the most recent printing of counterspell, they would get two counterspell with the MH2 art. 

I am not entirely sure how we could work around this. One solution would be to just accept it, and move on. Another would be to add a property to the RenderableCard object where you can see if `set` comes from the Scryfall responses or from the cards file, and we can assign art by only using the set code from the cards file.

2021-10-04 23:20 UTC, Haven-King requested changes
This looks like a pretty good start! There are some changes I'd like to see before merging it (I also haven't actually tested it yet). There are some other changes I'd make before putting this in a release, but those are a bit more big picture, so unless you're really eager, I'd be happy to make those after merging this PR.

2021-10-09 11:58 UTC, Gikkman commented on src/main/java/dev/hephaestus/proximity/cardart/ArtResolver.java
> +	}
I'm guessing you mean a Java `record`? I had to google it, I've never seen these before but then again, I mostly write Java 8 code. I've addressed this.

2021-10-09 12:02 UTC, Gikkman commented on src/main/java/dev/hephaestus/proximity/cardart/ArtRepository.java
> +	String findArt(RenderableCard card);
Yeah, good idea. I've moved the code around a bit, and made each repository return its own InputStreamWrapper (had to wrap it to be able to include the String that says where the art is loaded from, for the debug logger).

2021-10-09 12:11 UTC, Gikkman commented on src/main/java/dev/hephaestus/proximity/cardart/LocalArtRepository.java
> +			.orElse(null);
Done

2021-10-09 12:14 UTC, Gikkman commented on src/main/java/dev/hephaestus/proximity/xml/RenderableCard.java
> +
Without helper methods like this, the code risks get littered by magic string constants, without any further context. I really feel that it helps readability a lot by having helper methods like this. It also makes it much easier if, in the future, someone would need to find all places where the `set` is being used, since you can just look up the places where this method is used. 

If you are adamant, then sure I'll remove it, but I fail to see the problem with helper methods like this.

2021-10-16 22:07 UTC, Haven-King commented
Your changes look in line with what I requested in my previous review, but since then I have made some larger changes to Proximity, and think a different approach might be better. Most importantly, I've recently added scripting capabilities to templates. As much of the logic in this PR is Magic-specific, and therefore template-specific, I think it would be useful to provide a way for templates themselves to implement this behavior, and would love to have a conversation brainstorming what that might look like.

The entire `ArtLayer` layer type could likely be dropped, instead giving `ImageLayer`s the ability to source their images from places outside of the `TemplateSource`. Scripts could be given the ability to modify layer attributes (most relevantly for this use case, the source).

I'm not entirely sure the direction I'd like to go with this, but appreciate the work you've put in so far and would value your input on the matter.

2021-10-17 20:15 UTC, Haven-King commented
> [Moving art functionality to templates] puts a lot of difficulty into making them and updating/maintaining them

Remote resources ([currently used for set symbols](https://github.com/Haven-King/Proximity/blob/fb855067fa90b09a3f3c1af7c175619fe07cf2a7/run/templates/normal/template.xml#L33)) would allow individual templates to not have to worry about such things, so long as a centralized script source exists. Thankfully the JavaScript environment is so heavily sandboxed that the security concerns of running code sourced remotely are minimal.

> Access to harddrives and ability to make web requests are very powerful.

This is absolutely true, but we wouldn't be exposing the entirety of Java's file handling and web request capabilities. For files, it would likely be adequate to have two methods `getWorkingDirectory` and `exists`. They would then use those two methods and information about the cards to construct a file path and set the `ImageLayer`s source. As for sourcing web requests, that one would be even easier, I imagine. We'd simply ask them to provide a URL to query, and we'd do that on the Proximity side expecting a single JSON response.

Plugins are definitely an interesting idea. I think in theory, plugins and scripts would coexist, serving the exact same purpose and having access to the exact same tools but from two different environments.

I do think I would rather have a platform-agnostic system for image layers from the get-go, to avoid any pains of removing a platform-dependent system later on.

2021-10-18 07:03 UTC, Gikkman commented
> I do think I would rather have a platform-agnostic system for image layers from the get-go

In that case, if you feel this isn't a functionality that should be included at all, feel free to close the PR.

>  Remote resources (currently used for set symbols) would allow individual templates to not have to worry about such things, so long as a centralized script source exists.

I think I need to better try to communicate what I mean when I say templates risks becoming hard to maintain. I don't necessarily think of each template that's created by template creators, I am thinking of the template system.

I think the system is already a bit difficult to wrap your head around, because there is essentially code (or code-ish) coming from two places: java and the xml files, with templates already contains conditional operations and references java defined behaviors. By introducing a third source of logic (remote sourced scripts), the learning curve for new developers becomes very steep, and it risks creating a situation where the only one who really understands and can extend Proximity is you. 

Add to that that there are different languages involved, and they probably require different tooling or setups to develop and debug, I just have this nagging feeling that it might become really difficult to develop and debug. I've got some industry experience from solutions that looked really handy on paper and on initial implementation (in this case, sourcing remote code to handle template logic), but which became a real hassle to maintain 6 months down the line.

Sorry for sounding like a downer here, that's not my intention. I am really impressed by what you've got so far, and I really want to keep helping improving this, which is why I try to get my thoughts across.  Hope it's useful.

2021-12-04 14:34 UTC, closed without merging